title: 'Pixel Open'
baseline: 'Share, contribute to open source projects'
baseurl: 'https://pixel-open.org/'
description: 'Projets Open source pour Symfony, Wordpress, Prestashop, Sulu, Magento... proposé par Pixel Développement'
author:
    name: 'Team Pixel'
    url: 'https://www.pixel-developpement.com'
image: pixel-card.png
socials:
    github: https://github.com/Pixel-Open
language: en
menus:
  main:
    - id: index
      weight: 0
      enabled: false
    - id: projects
      name: Projects
      weight: 10
    - id: news
      name: News
      weight: 20
    - id: about
      name: About
      weight: 30
  footer:

    - id: projects
      name: Legal mention
      weight: 10


theme:
  - pwa
serviceworker:
  enabled: true
pagination:
  max: 6
metatags:
  jsonld: true
  articles: news
body:
  images:
    lazy:
      enabled: true
    caption:
      enabled: true
    resize:
      enabled: true
    responsive:
      enabled: true
    webp:
      enabled: true
    remote:
      enabled: true
  notes:
    enabled: true
  highlight:
    enabled: true
assets:
  images:
    optimize:
      enabled: true
    responsive:
      enabled: true
    webp:
      enabled: true